version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "8080:80"

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data:
